"use strict";
/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */
Object.defineProperty(exports, "__esModule", { value: true });
/* tslint:disable */
const capnp = require("capnp-ts");
const capnp_ts_1 = require("capnp-ts");
exports._capnpFileId = "d908e1cdf0dd8aff";
class PriceLevel extends capnp_ts_1.Struct {
    getPrice() { return capnp_ts_1.Struct.getFloat64(0, this); }
    setPrice(value) { capnp_ts_1.Struct.setFloat64(0, value, this); }
    getQty() { return capnp_ts_1.Struct.getUint64(8, this); }
    setQty(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    toString() { return "PriceLevel_" + super.toString(); }
}
PriceLevel._capnp = { displayName: "PriceLevel", id: "ddf005b307d37ebd", size: new capnp_ts_1.ObjectSize(16, 0) };
exports.PriceLevel = PriceLevel;
class ExchangeUserData extends capnp_ts_1.Struct {
    getUserID() { return capnp_ts_1.Struct.getText(0, this); }
    setUserID(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getOrderID() { return capnp_ts_1.Struct.getText(1, this); }
    setOrderID(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getCurrency() { return capnp_ts_1.Struct.getText(2, this); }
    setCurrency(value) { capnp_ts_1.Struct.setText(2, value, this); }
    getQty() { return capnp_ts_1.Struct.getUint64(0, this); }
    setQty(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "ExchangeUserData_" + super.toString(); }
}
ExchangeUserData._capnp = { displayName: "ExchangeUserData", id: "c58198e650b0fc9d", size: new capnp_ts_1.ObjectSize(8, 3) };
exports.ExchangeUserData = ExchangeUserData;
class APIMessage_Bar extends capnp_ts_1.Struct {
    getBuyingCurrency() { return capnp_ts_1.Struct.getText(0, this); }
    setBuyingCurrency(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getSellingCurrency() { return capnp_ts_1.Struct.getText(1, this); }
    setSellingCurrency(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getResolution() { return capnp_ts_1.Struct.getUint64(0, this); }
    setResolution(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getTime() { return capnp_ts_1.Struct.getUint64(8, this); }
    setTime(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getMaxPrice() { return capnp_ts_1.Struct.getFloat64(24, this); }
    setMaxPrice(value) { capnp_ts_1.Struct.setFloat64(24, value, this); }
    getMinPrice() { return capnp_ts_1.Struct.getFloat64(32, this); }
    setMinPrice(value) { capnp_ts_1.Struct.setFloat64(32, value, this); }
    getOpenPrice() { return capnp_ts_1.Struct.getFloat64(40, this); }
    setOpenPrice(value) { capnp_ts_1.Struct.setFloat64(40, value, this); }
    getClosePrice() { return capnp_ts_1.Struct.getFloat64(48, this); }
    setClosePrice(value) { capnp_ts_1.Struct.setFloat64(48, value, this); }
    getVolume() { return capnp_ts_1.Struct.getUint64(56, this); }
    setVolume(value) { capnp_ts_1.Struct.setUint64(56, value, this); }
    toString() { return "APIMessage_Bar_" + super.toString(); }
}
APIMessage_Bar._capnp = { displayName: "bar", id: "d33018d46e73e8ac", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_Bar = APIMessage_Bar;
class APIMessage_Book extends capnp_ts_1.Struct {
    getSeqNumber() { return capnp_ts_1.Struct.getUint64(0, this); }
    setSeqNumber(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getBaseCurrency() { return capnp_ts_1.Struct.getText(0, this); }
    setBaseCurrency(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getQuoteCurrency() { return capnp_ts_1.Struct.getText(1, this); }
    setQuoteCurrency(value) { capnp_ts_1.Struct.setText(1, value, this); }
    adoptBids(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(2, this)); }
    disownBids() { return capnp_ts_1.Struct.disown(this.getBids()); }
    getBids() { return capnp_ts_1.Struct.getList(2, APIMessage_Book._Bids, this); }
    hasBids() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(2, this)); }
    initBids(length) { return capnp_ts_1.Struct.initList(2, APIMessage_Book._Bids, length, this); }
    setBids(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(2, this)); }
    adoptAsks(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(3, this)); }
    disownAsks() { return capnp_ts_1.Struct.disown(this.getAsks()); }
    getAsks() { return capnp_ts_1.Struct.getList(3, APIMessage_Book._Asks, this); }
    hasAsks() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(3, this)); }
    initAsks(length) { return capnp_ts_1.Struct.initList(3, APIMessage_Book._Asks, length, this); }
    setAsks(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(3, this)); }
    toString() { return "APIMessage_Book_" + super.toString(); }
}
APIMessage_Book._capnp = { displayName: "book", id: "bf5360d47d6d6cda", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_Book = APIMessage_Book;
class APIMessage_InfoMessage extends capnp_ts_1.Struct {
    getUserID() { return capnp_ts_1.Struct.getText(0, this); }
    setUserID(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getOrderID() { return capnp_ts_1.Struct.getText(1, this); }
    setOrderID(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getText() { return capnp_ts_1.Struct.getText(2, this); }
    setText(value) { capnp_ts_1.Struct.setText(2, value, this); }
    toString() { return "APIMessage_InfoMessage_" + super.toString(); }
}
APIMessage_InfoMessage._capnp = { displayName: "infoMessage", id: "aae8173076328360", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_InfoMessage = APIMessage_InfoMessage;
class APIMessage_Exchange extends capnp_ts_1.Struct {
    getSeqNumber() { return capnp_ts_1.Struct.getUint64(0, this); }
    setSeqNumber(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getExecutionTime() { return capnp_ts_1.Struct.getUint64(8, this); }
    setExecutionTime(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    adoptExchangeUserData1(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(0, this)); }
    disownExchangeUserData1() { return capnp_ts_1.Struct.disown(this.getExchangeUserData1()); }
    getExchangeUserData1() { return capnp_ts_1.Struct.getStruct(0, ExchangeUserData, this); }
    hasExchangeUserData1() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(0, this)); }
    initExchangeUserData1() { return capnp_ts_1.Struct.initStructAt(0, ExchangeUserData, this); }
    setExchangeUserData1(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(0, this)); }
    adoptExchangeUserData2(value) { capnp_ts_1.Struct.adopt(value, capnp_ts_1.Struct.getPointer(1, this)); }
    disownExchangeUserData2() { return capnp_ts_1.Struct.disown(this.getExchangeUserData2()); }
    getExchangeUserData2() { return capnp_ts_1.Struct.getStruct(1, ExchangeUserData, this); }
    hasExchangeUserData2() { return !capnp_ts_1.Struct.isNull(capnp_ts_1.Struct.getPointer(1, this)); }
    initExchangeUserData2() { return capnp_ts_1.Struct.initStructAt(1, ExchangeUserData, this); }
    setExchangeUserData2(value) { capnp_ts_1.Struct.copyFrom(value, capnp_ts_1.Struct.getPointer(1, this)); }
    toString() { return "APIMessage_Exchange_" + super.toString(); }
}
APIMessage_Exchange._capnp = { displayName: "exchange", id: "fd9e977eab49627f", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_Exchange = APIMessage_Exchange;
class APIMessage_SyncStatus extends capnp_ts_1.Struct {
    getNextSeqNumber() { return capnp_ts_1.Struct.getUint64(0, this); }
    setNextSeqNumber(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "APIMessage_SyncStatus_" + super.toString(); }
}
APIMessage_SyncStatus._capnp = { displayName: "syncStatus", id: "a7b27b82602f3d29", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_SyncStatus = APIMessage_SyncStatus;
class APIMessage_ActiveOrdersRequest extends capnp_ts_1.Struct {
    getUserID() { return capnp_ts_1.Struct.getText(0, this); }
    setUserID(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "APIMessage_ActiveOrdersRequest_" + super.toString(); }
}
APIMessage_ActiveOrdersRequest._capnp = { displayName: "activeOrdersRequest", id: "c22184fc1ee5ea66", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_ActiveOrdersRequest = APIMessage_ActiveOrdersRequest;
class APIMessage_OrderCancelRequest extends capnp_ts_1.Struct {
    getUserID() { return capnp_ts_1.Struct.getText(1, this); }
    setUserID(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getOrderID() { return capnp_ts_1.Struct.getText(0, this); }
    setOrderID(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "APIMessage_OrderCancelRequest_" + super.toString(); }
}
APIMessage_OrderCancelRequest._capnp = { displayName: "orderCancelRequest", id: "fe2f17ab07f8d86e", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_OrderCancelRequest = APIMessage_OrderCancelRequest;
class APIMessage_BarRequest extends capnp_ts_1.Struct {
    getBuyingCurrency() { return capnp_ts_1.Struct.getText(0, this); }
    setBuyingCurrency(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getSellingCurrency() { return capnp_ts_1.Struct.getText(1, this); }
    setSellingCurrency(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getResolution() { return capnp_ts_1.Struct.getUint64(0, this); }
    setResolution(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getFrom() { return capnp_ts_1.Struct.getUint64(8, this); }
    setFrom(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getTo() { return capnp_ts_1.Struct.getUint64(24, this); }
    setTo(value) { capnp_ts_1.Struct.setUint64(24, value, this); }
    toString() { return "APIMessage_BarRequest_" + super.toString(); }
}
APIMessage_BarRequest._capnp = { displayName: "barRequest", id: "fc9f8de59e5be187", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_BarRequest = APIMessage_BarRequest;
class APIMessage_NewOrderRequest extends capnp_ts_1.Struct {
    getUserID() { return capnp_ts_1.Struct.getText(0, this); }
    setUserID(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getOrderID() { return capnp_ts_1.Struct.getText(1, this); }
    setOrderID(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getOrderType() { return capnp_ts_1.Struct.getText(2, this); }
    setOrderType(value) { capnp_ts_1.Struct.setText(2, value, this); }
    getSellingCurrency() { return capnp_ts_1.Struct.getText(3, this); }
    setSellingCurrency(value) { capnp_ts_1.Struct.setText(3, value, this); }
    getSellingQty() { return capnp_ts_1.Struct.getUint64(0, this); }
    setSellingQty(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getBuyingCurrency() { return capnp_ts_1.Struct.getText(4, this); }
    setBuyingCurrency(value) { capnp_ts_1.Struct.setText(4, value, this); }
    getBuyingQty() { return capnp_ts_1.Struct.getUint64(8, this); }
    setBuyingQty(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getUserData() { return capnp_ts_1.Struct.getText(5, this); }
    setUserData(value) { capnp_ts_1.Struct.setText(5, value, this); }
    toString() { return "APIMessage_NewOrderRequest_" + super.toString(); }
}
APIMessage_NewOrderRequest._capnp = { displayName: "newOrderRequest", id: "880175a4d7dae0f7", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_NewOrderRequest = APIMessage_NewOrderRequest;
class APIMessage_OrderStatus extends capnp_ts_1.Struct {
    getSeqNumber() { return capnp_ts_1.Struct.getUint64(0, this); }
    setSeqNumber(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    getUserID() { return capnp_ts_1.Struct.getText(0, this); }
    setUserID(value) { capnp_ts_1.Struct.setText(0, value, this); }
    getOrderID() { return capnp_ts_1.Struct.getText(1, this); }
    setOrderID(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getCreationTime() { return capnp_ts_1.Struct.getUint64(8, this); }
    setCreationTime(value) { capnp_ts_1.Struct.setUint64(8, value, this); }
    getCompletionTime() { return capnp_ts_1.Struct.getUint64(24, this); }
    setCompletionTime(value) { capnp_ts_1.Struct.setUint64(24, value, this); }
    getOrderType() { return capnp_ts_1.Struct.getText(2, this); }
    setOrderType(value) { capnp_ts_1.Struct.setText(2, value, this); }
    getSellingCurrency() { return capnp_ts_1.Struct.getText(3, this); }
    setSellingCurrency(value) { capnp_ts_1.Struct.setText(3, value, this); }
    getSoldQty() { return capnp_ts_1.Struct.getUint64(32, this); }
    setSoldQty(value) { capnp_ts_1.Struct.setUint64(32, value, this); }
    getOrigSellingQty() { return capnp_ts_1.Struct.getUint64(40, this); }
    setOrigSellingQty(value) { capnp_ts_1.Struct.setUint64(40, value, this); }
    getBuyingCurrency() { return capnp_ts_1.Struct.getText(4, this); }
    setBuyingCurrency(value) { capnp_ts_1.Struct.setText(4, value, this); }
    getBoughtQty() { return capnp_ts_1.Struct.getUint64(48, this); }
    setBoughtQty(value) { capnp_ts_1.Struct.setUint64(48, value, this); }
    getOrigBuyingQty() { return capnp_ts_1.Struct.getUint64(56, this); }
    setOrigBuyingQty(value) { capnp_ts_1.Struct.setUint64(56, value, this); }
    getUserData() { return capnp_ts_1.Struct.getText(5, this); }
    setUserData(value) { capnp_ts_1.Struct.setText(5, value, this); }
    toString() { return "APIMessage_OrderStatus_" + super.toString(); }
}
APIMessage_OrderStatus._capnp = { displayName: "orderStatus", id: "c17064d69428550f", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_OrderStatus = APIMessage_OrderStatus;
class APIMessage_OrderStatusRequest extends capnp_ts_1.Struct {
    getUserID() { return capnp_ts_1.Struct.getText(1, this); }
    setUserID(value) { capnp_ts_1.Struct.setText(1, value, this); }
    getOrderID() { return capnp_ts_1.Struct.getText(0, this); }
    setOrderID(value) { capnp_ts_1.Struct.setText(0, value, this); }
    toString() { return "APIMessage_OrderStatusRequest_" + super.toString(); }
}
APIMessage_OrderStatusRequest._capnp = { displayName: "orderStatusRequest", id: "bf99dd6e06001d4e", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_OrderStatusRequest = APIMessage_OrderStatusRequest;
class APIMessage_SyncRequest extends capnp_ts_1.Struct {
    getFrom() { return capnp_ts_1.Struct.getUint64(0, this); }
    setFrom(value) { capnp_ts_1.Struct.setUint64(0, value, this); }
    toString() { return "APIMessage_SyncRequest_" + super.toString(); }
}
APIMessage_SyncRequest._capnp = { displayName: "syncRequest", id: "f426d6cb04ffcfda", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage_SyncRequest = APIMessage_SyncRequest;
var APIMessage_Which;
(function (APIMessage_Which) {
    APIMessage_Which[APIMessage_Which["SYNC_REQUEST"] = 3] = "SYNC_REQUEST";
    APIMessage_Which[APIMessage_Which["NEW_ORDER_REQUEST"] = 0] = "NEW_ORDER_REQUEST";
    APIMessage_Which[APIMessage_Which["ORDER_STATUS_REQUEST"] = 1] = "ORDER_STATUS_REQUEST";
    APIMessage_Which[APIMessage_Which["ACTIVE_ORDERS_REQUEST"] = 4] = "ACTIVE_ORDERS_REQUEST";
    APIMessage_Which[APIMessage_Which["ORDER_CANCEL_REQUEST"] = 2] = "ORDER_CANCEL_REQUEST";
    APIMessage_Which[APIMessage_Which["SYNC_STATUS"] = 5] = "SYNC_STATUS";
    APIMessage_Which[APIMessage_Which["ORDER_STATUS"] = 6] = "ORDER_STATUS";
    APIMessage_Which[APIMessage_Which["EXCHANGE"] = 7] = "EXCHANGE";
    APIMessage_Which[APIMessage_Which["INFO_MESSAGE"] = 8] = "INFO_MESSAGE";
    APIMessage_Which[APIMessage_Which["BOOK"] = 9] = "BOOK";
    APIMessage_Which[APIMessage_Which["BAR"] = 10] = "BAR";
    APIMessage_Which[APIMessage_Which["BAR_REQUEST"] = 11] = "BAR_REQUEST";
})(APIMessage_Which = exports.APIMessage_Which || (exports.APIMessage_Which = {}));
class APIMessage extends capnp_ts_1.Struct {
    getSyncRequest() {
        capnp_ts_1.Struct.testWhich("syncRequest", capnp_ts_1.Struct.getUint16(16, this), 3, this);
        return capnp_ts_1.Struct.getAs(APIMessage_SyncRequest, this);
    }
    initSyncRequest() {
        capnp_ts_1.Struct.setUint16(16, 3, this);
        return capnp_ts_1.Struct.getAs(APIMessage_SyncRequest, this);
    }
    isSyncRequest() { return capnp_ts_1.Struct.getUint16(16, this) === 3; }
    setSyncRequest() { capnp_ts_1.Struct.setUint16(16, 3, this); }
    getNewOrderRequest() {
        capnp_ts_1.Struct.testWhich("newOrderRequest", capnp_ts_1.Struct.getUint16(16, this), 0, this);
        return capnp_ts_1.Struct.getAs(APIMessage_NewOrderRequest, this);
    }
    initNewOrderRequest() {
        capnp_ts_1.Struct.setUint16(16, 0, this);
        return capnp_ts_1.Struct.getAs(APIMessage_NewOrderRequest, this);
    }
    isNewOrderRequest() { return capnp_ts_1.Struct.getUint16(16, this) === 0; }
    setNewOrderRequest() { capnp_ts_1.Struct.setUint16(16, 0, this); }
    getOrderStatusRequest() {
        capnp_ts_1.Struct.testWhich("orderStatusRequest", capnp_ts_1.Struct.getUint16(16, this), 1, this);
        return capnp_ts_1.Struct.getAs(APIMessage_OrderStatusRequest, this);
    }
    initOrderStatusRequest() {
        capnp_ts_1.Struct.setUint16(16, 1, this);
        return capnp_ts_1.Struct.getAs(APIMessage_OrderStatusRequest, this);
    }
    isOrderStatusRequest() { return capnp_ts_1.Struct.getUint16(16, this) === 1; }
    setOrderStatusRequest() { capnp_ts_1.Struct.setUint16(16, 1, this); }
    getActiveOrdersRequest() {
        capnp_ts_1.Struct.testWhich("activeOrdersRequest", capnp_ts_1.Struct.getUint16(16, this), 4, this);
        return capnp_ts_1.Struct.getAs(APIMessage_ActiveOrdersRequest, this);
    }
    initActiveOrdersRequest() {
        capnp_ts_1.Struct.setUint16(16, 4, this);
        return capnp_ts_1.Struct.getAs(APIMessage_ActiveOrdersRequest, this);
    }
    isActiveOrdersRequest() { return capnp_ts_1.Struct.getUint16(16, this) === 4; }
    setActiveOrdersRequest() { capnp_ts_1.Struct.setUint16(16, 4, this); }
    getOrderCancelRequest() {
        capnp_ts_1.Struct.testWhich("orderCancelRequest", capnp_ts_1.Struct.getUint16(16, this), 2, this);
        return capnp_ts_1.Struct.getAs(APIMessage_OrderCancelRequest, this);
    }
    initOrderCancelRequest() {
        capnp_ts_1.Struct.setUint16(16, 2, this);
        return capnp_ts_1.Struct.getAs(APIMessage_OrderCancelRequest, this);
    }
    isOrderCancelRequest() { return capnp_ts_1.Struct.getUint16(16, this) === 2; }
    setOrderCancelRequest() { capnp_ts_1.Struct.setUint16(16, 2, this); }
    getSyncStatus() {
        capnp_ts_1.Struct.testWhich("syncStatus", capnp_ts_1.Struct.getUint16(16, this), 5, this);
        return capnp_ts_1.Struct.getAs(APIMessage_SyncStatus, this);
    }
    initSyncStatus() {
        capnp_ts_1.Struct.setUint16(16, 5, this);
        return capnp_ts_1.Struct.getAs(APIMessage_SyncStatus, this);
    }
    isSyncStatus() { return capnp_ts_1.Struct.getUint16(16, this) === 5; }
    setSyncStatus() { capnp_ts_1.Struct.setUint16(16, 5, this); }
    getOrderStatus() {
        capnp_ts_1.Struct.testWhich("orderStatus", capnp_ts_1.Struct.getUint16(16, this), 6, this);
        return capnp_ts_1.Struct.getAs(APIMessage_OrderStatus, this);
    }
    initOrderStatus() {
        capnp_ts_1.Struct.setUint16(16, 6, this);
        return capnp_ts_1.Struct.getAs(APIMessage_OrderStatus, this);
    }
    isOrderStatus() { return capnp_ts_1.Struct.getUint16(16, this) === 6; }
    setOrderStatus() { capnp_ts_1.Struct.setUint16(16, 6, this); }
    getExchange() {
        capnp_ts_1.Struct.testWhich("exchange", capnp_ts_1.Struct.getUint16(16, this), 7, this);
        return capnp_ts_1.Struct.getAs(APIMessage_Exchange, this);
    }
    initExchange() {
        capnp_ts_1.Struct.setUint16(16, 7, this);
        return capnp_ts_1.Struct.getAs(APIMessage_Exchange, this);
    }
    isExchange() { return capnp_ts_1.Struct.getUint16(16, this) === 7; }
    setExchange() { capnp_ts_1.Struct.setUint16(16, 7, this); }
    getInfoMessage() {
        capnp_ts_1.Struct.testWhich("infoMessage", capnp_ts_1.Struct.getUint16(16, this), 8, this);
        return capnp_ts_1.Struct.getAs(APIMessage_InfoMessage, this);
    }
    initInfoMessage() {
        capnp_ts_1.Struct.setUint16(16, 8, this);
        return capnp_ts_1.Struct.getAs(APIMessage_InfoMessage, this);
    }
    isInfoMessage() { return capnp_ts_1.Struct.getUint16(16, this) === 8; }
    setInfoMessage() { capnp_ts_1.Struct.setUint16(16, 8, this); }
    getBook() {
        capnp_ts_1.Struct.testWhich("book", capnp_ts_1.Struct.getUint16(16, this), 9, this);
        return capnp_ts_1.Struct.getAs(APIMessage_Book, this);
    }
    initBook() {
        capnp_ts_1.Struct.setUint16(16, 9, this);
        return capnp_ts_1.Struct.getAs(APIMessage_Book, this);
    }
    isBook() { return capnp_ts_1.Struct.getUint16(16, this) === 9; }
    setBook() { capnp_ts_1.Struct.setUint16(16, 9, this); }
    getBar() {
        capnp_ts_1.Struct.testWhich("bar", capnp_ts_1.Struct.getUint16(16, this), 10, this);
        return capnp_ts_1.Struct.getAs(APIMessage_Bar, this);
    }
    initBar() {
        capnp_ts_1.Struct.setUint16(16, 10, this);
        return capnp_ts_1.Struct.getAs(APIMessage_Bar, this);
    }
    isBar() { return capnp_ts_1.Struct.getUint16(16, this) === 10; }
    setBar() { capnp_ts_1.Struct.setUint16(16, 10, this); }
    getBarRequest() {
        capnp_ts_1.Struct.testWhich("barRequest", capnp_ts_1.Struct.getUint16(16, this), 11, this);
        return capnp_ts_1.Struct.getAs(APIMessage_BarRequest, this);
    }
    initBarRequest() {
        capnp_ts_1.Struct.setUint16(16, 11, this);
        return capnp_ts_1.Struct.getAs(APIMessage_BarRequest, this);
    }
    isBarRequest() { return capnp_ts_1.Struct.getUint16(16, this) === 11; }
    setBarRequest() { capnp_ts_1.Struct.setUint16(16, 11, this); }
    toString() { return "APIMessage_" + super.toString(); }
    which() { return capnp_ts_1.Struct.getUint16(16, this); }
}
APIMessage.SYNC_REQUEST = APIMessage_Which.SYNC_REQUEST;
APIMessage.NEW_ORDER_REQUEST = APIMessage_Which.NEW_ORDER_REQUEST;
APIMessage.ORDER_STATUS_REQUEST = APIMessage_Which.ORDER_STATUS_REQUEST;
APIMessage.ACTIVE_ORDERS_REQUEST = APIMessage_Which.ACTIVE_ORDERS_REQUEST;
APIMessage.ORDER_CANCEL_REQUEST = APIMessage_Which.ORDER_CANCEL_REQUEST;
APIMessage.SYNC_STATUS = APIMessage_Which.SYNC_STATUS;
APIMessage.ORDER_STATUS = APIMessage_Which.ORDER_STATUS;
APIMessage.EXCHANGE = APIMessage_Which.EXCHANGE;
APIMessage.INFO_MESSAGE = APIMessage_Which.INFO_MESSAGE;
APIMessage.BOOK = APIMessage_Which.BOOK;
APIMessage.BAR = APIMessage_Which.BAR;
APIMessage.BAR_REQUEST = APIMessage_Which.BAR_REQUEST;
APIMessage._capnp = { displayName: "APIMessage", id: "d99512946cd0cd3f", size: new capnp_ts_1.ObjectSize(64, 6) };
exports.APIMessage = APIMessage;
APIMessage_Book._Bids = capnp.CompositeList(PriceLevel);
APIMessage_Book._Asks = capnp.CompositeList(PriceLevel);
