/**
 * This file has been automatically generated by the [capnpc-ts utility](https://github.com/jdiaz5513/capnp-ts).
 */

/* tslint:disable */

import * as capnp from "capnp-ts";
import { ObjectSize as __O, Struct as __S } from 'capnp-ts';
export const _capnpFileId = "d908e1cdf0dd8aff";
export class PriceLevel extends __S {
    static readonly _capnp = { displayName: "PriceLevel", id: "ddf005b307d37ebd", size: new __O(16, 0) };
    getPrice(): number { return __S.getFloat64(0, this); }
    setPrice(value: number): void { __S.setFloat64(0, value, this); }
    getQty(): capnp.Uint64 { return __S.getUint64(8, this); }
    setQty(value: capnp.Uint64): void { __S.setUint64(8, value, this); }
    toString(): string { return "PriceLevel_" + super.toString(); }
}
export class ExchangeUserData extends __S {
    static readonly _capnp = { displayName: "ExchangeUserData", id: "c58198e650b0fc9d", size: new __O(8, 3) };
    getUserID(): string { return __S.getText(0, this); }
    setUserID(value: string): void { __S.setText(0, value, this); }
    getOrderID(): string { return __S.getText(1, this); }
    setOrderID(value: string): void { __S.setText(1, value, this); }
    getCurrency(): string { return __S.getText(2, this); }
    setCurrency(value: string): void { __S.setText(2, value, this); }
    getQty(): capnp.Uint64 { return __S.getUint64(0, this); }
    setQty(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    toString(): string { return "ExchangeUserData_" + super.toString(); }
}
export class APIMessage_Bar extends __S {
    static readonly _capnp = { displayName: "bar", id: "d33018d46e73e8ac", size: new __O(64, 6) };
    getBuyingCurrency(): string { return __S.getText(0, this); }
    setBuyingCurrency(value: string): void { __S.setText(0, value, this); }
    getSellingCurrency(): string { return __S.getText(1, this); }
    setSellingCurrency(value: string): void { __S.setText(1, value, this); }
    getResolution(): capnp.Uint64 { return __S.getUint64(0, this); }
    setResolution(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    getTime(): capnp.Uint64 { return __S.getUint64(8, this); }
    setTime(value: capnp.Uint64): void { __S.setUint64(8, value, this); }
    getMaxPrice(): number { return __S.getFloat64(24, this); }
    setMaxPrice(value: number): void { __S.setFloat64(24, value, this); }
    getMinPrice(): number { return __S.getFloat64(32, this); }
    setMinPrice(value: number): void { __S.setFloat64(32, value, this); }
    getOpenPrice(): number { return __S.getFloat64(40, this); }
    setOpenPrice(value: number): void { __S.setFloat64(40, value, this); }
    getClosePrice(): number { return __S.getFloat64(48, this); }
    setClosePrice(value: number): void { __S.setFloat64(48, value, this); }
    getVolume(): capnp.Uint64 { return __S.getUint64(56, this); }
    setVolume(value: capnp.Uint64): void { __S.setUint64(56, value, this); }
    toString(): string { return "APIMessage_Bar_" + super.toString(); }
}
export class APIMessage_Book extends __S {
    static readonly _capnp = { displayName: "book", id: "bf5360d47d6d6cda", size: new __O(64, 6) };
    static _Bids: capnp.ListCtor<PriceLevel>;
    static _Asks: capnp.ListCtor<PriceLevel>;
    getSeqNumber(): capnp.Uint64 { return __S.getUint64(0, this); }
    setSeqNumber(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    getBaseCurrency(): string { return __S.getText(0, this); }
    setBaseCurrency(value: string): void { __S.setText(0, value, this); }
    getQuoteCurrency(): string { return __S.getText(1, this); }
    setQuoteCurrency(value: string): void { __S.setText(1, value, this); }
    adoptBids(value: capnp.Orphan<capnp.List<PriceLevel>>): void { __S.adopt(value, __S.getPointer(2, this)); }
    disownBids(): capnp.Orphan<capnp.List<PriceLevel>> { return __S.disown(this.getBids()); }
    getBids(): capnp.List<PriceLevel> { return __S.getList(2, APIMessage_Book._Bids, this); }
    hasBids(): boolean { return !__S.isNull(__S.getPointer(2, this)); }
    initBids(length: number): capnp.List<PriceLevel> { return __S.initList(2, APIMessage_Book._Bids, length, this); }
    setBids(value: capnp.List<PriceLevel>): void { __S.copyFrom(value, __S.getPointer(2, this)); }
    adoptAsks(value: capnp.Orphan<capnp.List<PriceLevel>>): void { __S.adopt(value, __S.getPointer(3, this)); }
    disownAsks(): capnp.Orphan<capnp.List<PriceLevel>> { return __S.disown(this.getAsks()); }
    getAsks(): capnp.List<PriceLevel> { return __S.getList(3, APIMessage_Book._Asks, this); }
    hasAsks(): boolean { return !__S.isNull(__S.getPointer(3, this)); }
    initAsks(length: number): capnp.List<PriceLevel> { return __S.initList(3, APIMessage_Book._Asks, length, this); }
    setAsks(value: capnp.List<PriceLevel>): void { __S.copyFrom(value, __S.getPointer(3, this)); }
    toString(): string { return "APIMessage_Book_" + super.toString(); }
}
export class APIMessage_InfoMessage extends __S {
    static readonly _capnp = { displayName: "infoMessage", id: "aae8173076328360", size: new __O(64, 6) };
    getUserID(): string { return __S.getText(0, this); }
    setUserID(value: string): void { __S.setText(0, value, this); }
    getOrderID(): string { return __S.getText(1, this); }
    setOrderID(value: string): void { __S.setText(1, value, this); }
    getText(): string { return __S.getText(2, this); }
    setText(value: string): void { __S.setText(2, value, this); }
    toString(): string { return "APIMessage_InfoMessage_" + super.toString(); }
}
export class APIMessage_Exchange extends __S {
    static readonly _capnp = { displayName: "exchange", id: "fd9e977eab49627f", size: new __O(64, 6) };
    getSeqNumber(): capnp.Uint64 { return __S.getUint64(0, this); }
    setSeqNumber(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    getExecutionTime(): capnp.Uint64 { return __S.getUint64(8, this); }
    setExecutionTime(value: capnp.Uint64): void { __S.setUint64(8, value, this); }
    adoptExchangeUserData1(value: capnp.Orphan<ExchangeUserData>): void { __S.adopt(value, __S.getPointer(0, this)); }
    disownExchangeUserData1(): capnp.Orphan<ExchangeUserData> { return __S.disown(this.getExchangeUserData1()); }
    getExchangeUserData1(): ExchangeUserData { return __S.getStruct(0, ExchangeUserData, this); }
    hasExchangeUserData1(): boolean { return !__S.isNull(__S.getPointer(0, this)); }
    initExchangeUserData1(): ExchangeUserData { return __S.initStructAt(0, ExchangeUserData, this); }
    setExchangeUserData1(value: ExchangeUserData): void { __S.copyFrom(value, __S.getPointer(0, this)); }
    adoptExchangeUserData2(value: capnp.Orphan<ExchangeUserData>): void { __S.adopt(value, __S.getPointer(1, this)); }
    disownExchangeUserData2(): capnp.Orphan<ExchangeUserData> { return __S.disown(this.getExchangeUserData2()); }
    getExchangeUserData2(): ExchangeUserData { return __S.getStruct(1, ExchangeUserData, this); }
    hasExchangeUserData2(): boolean { return !__S.isNull(__S.getPointer(1, this)); }
    initExchangeUserData2(): ExchangeUserData { return __S.initStructAt(1, ExchangeUserData, this); }
    setExchangeUserData2(value: ExchangeUserData): void { __S.copyFrom(value, __S.getPointer(1, this)); }
    toString(): string { return "APIMessage_Exchange_" + super.toString(); }
}
export class APIMessage_SyncStatus extends __S {
    static readonly _capnp = { displayName: "syncStatus", id: "a7b27b82602f3d29", size: new __O(64, 6) };
    getNextSeqNumber(): capnp.Uint64 { return __S.getUint64(0, this); }
    setNextSeqNumber(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    toString(): string { return "APIMessage_SyncStatus_" + super.toString(); }
}
export class APIMessage_ActiveOrdersRequest extends __S {
    static readonly _capnp = { displayName: "activeOrdersRequest", id: "c22184fc1ee5ea66", size: new __O(64, 6) };
    getUserID(): string { return __S.getText(0, this); }
    setUserID(value: string): void { __S.setText(0, value, this); }
    toString(): string { return "APIMessage_ActiveOrdersRequest_" + super.toString(); }
}
export class APIMessage_OrderCancelRequest extends __S {
    static readonly _capnp = { displayName: "orderCancelRequest", id: "fe2f17ab07f8d86e", size: new __O(64, 6) };
    getUserID(): string { return __S.getText(1, this); }
    setUserID(value: string): void { __S.setText(1, value, this); }
    getOrderID(): string { return __S.getText(0, this); }
    setOrderID(value: string): void { __S.setText(0, value, this); }
    toString(): string { return "APIMessage_OrderCancelRequest_" + super.toString(); }
}
export class APIMessage_BarRequest extends __S {
    static readonly _capnp = { displayName: "barRequest", id: "fc9f8de59e5be187", size: new __O(64, 6) };
    getBuyingCurrency(): string { return __S.getText(0, this); }
    setBuyingCurrency(value: string): void { __S.setText(0, value, this); }
    getSellingCurrency(): string { return __S.getText(1, this); }
    setSellingCurrency(value: string): void { __S.setText(1, value, this); }
    getResolution(): capnp.Uint64 { return __S.getUint64(0, this); }
    setResolution(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    getFrom(): capnp.Uint64 { return __S.getUint64(8, this); }
    setFrom(value: capnp.Uint64): void { __S.setUint64(8, value, this); }
    getTo(): capnp.Uint64 { return __S.getUint64(24, this); }
    setTo(value: capnp.Uint64): void { __S.setUint64(24, value, this); }
    toString(): string { return "APIMessage_BarRequest_" + super.toString(); }
}
export class APIMessage_NewOrderRequest extends __S {
    static readonly _capnp = { displayName: "newOrderRequest", id: "880175a4d7dae0f7", size: new __O(64, 6) };
    getUserID(): string { return __S.getText(0, this); }
    setUserID(value: string): void { __S.setText(0, value, this); }
    getOrderID(): string { return __S.getText(1, this); }
    setOrderID(value: string): void { __S.setText(1, value, this); }
    getOrderType(): string { return __S.getText(2, this); }
    setOrderType(value: string): void { __S.setText(2, value, this); }
    getSellingCurrency(): string { return __S.getText(3, this); }
    setSellingCurrency(value: string): void { __S.setText(3, value, this); }
    getSellingQty(): capnp.Uint64 { return __S.getUint64(0, this); }
    setSellingQty(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    getBuyingCurrency(): string { return __S.getText(4, this); }
    setBuyingCurrency(value: string): void { __S.setText(4, value, this); }
    getBuyingQty(): capnp.Uint64 { return __S.getUint64(8, this); }
    setBuyingQty(value: capnp.Uint64): void { __S.setUint64(8, value, this); }
    getUserData(): string { return __S.getText(5, this); }
    setUserData(value: string): void { __S.setText(5, value, this); }
    toString(): string { return "APIMessage_NewOrderRequest_" + super.toString(); }
}
export class APIMessage_OrderStatus extends __S {
    static readonly _capnp = { displayName: "orderStatus", id: "c17064d69428550f", size: new __O(64, 6) };
    getSeqNumber(): capnp.Uint64 { return __S.getUint64(0, this); }
    setSeqNumber(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    getUserID(): string { return __S.getText(0, this); }
    setUserID(value: string): void { __S.setText(0, value, this); }
    getOrderID(): string { return __S.getText(1, this); }
    setOrderID(value: string): void { __S.setText(1, value, this); }
    getCreationTime(): capnp.Uint64 { return __S.getUint64(8, this); }
    setCreationTime(value: capnp.Uint64): void { __S.setUint64(8, value, this); }
    getCompletionTime(): capnp.Uint64 { return __S.getUint64(24, this); }
    setCompletionTime(value: capnp.Uint64): void { __S.setUint64(24, value, this); }
    getOrderType(): string { return __S.getText(2, this); }
    setOrderType(value: string): void { __S.setText(2, value, this); }
    getSellingCurrency(): string { return __S.getText(3, this); }
    setSellingCurrency(value: string): void { __S.setText(3, value, this); }
    getSoldQty(): capnp.Uint64 { return __S.getUint64(32, this); }
    setSoldQty(value: capnp.Uint64): void { __S.setUint64(32, value, this); }
    getOrigSellingQty(): capnp.Uint64 { return __S.getUint64(40, this); }
    setOrigSellingQty(value: capnp.Uint64): void { __S.setUint64(40, value, this); }
    getBuyingCurrency(): string { return __S.getText(4, this); }
    setBuyingCurrency(value: string): void { __S.setText(4, value, this); }
    getBoughtQty(): capnp.Uint64 { return __S.getUint64(48, this); }
    setBoughtQty(value: capnp.Uint64): void { __S.setUint64(48, value, this); }
    getOrigBuyingQty(): capnp.Uint64 { return __S.getUint64(56, this); }
    setOrigBuyingQty(value: capnp.Uint64): void { __S.setUint64(56, value, this); }
    getUserData(): string { return __S.getText(5, this); }
    setUserData(value: string): void { __S.setText(5, value, this); }
    toString(): string { return "APIMessage_OrderStatus_" + super.toString(); }
}
export class APIMessage_OrderStatusRequest extends __S {
    static readonly _capnp = { displayName: "orderStatusRequest", id: "bf99dd6e06001d4e", size: new __O(64, 6) };
    getUserID(): string { return __S.getText(1, this); }
    setUserID(value: string): void { __S.setText(1, value, this); }
    getOrderID(): string { return __S.getText(0, this); }
    setOrderID(value: string): void { __S.setText(0, value, this); }
    toString(): string { return "APIMessage_OrderStatusRequest_" + super.toString(); }
}
export class APIMessage_SyncRequest extends __S {
    static readonly _capnp = { displayName: "syncRequest", id: "f426d6cb04ffcfda", size: new __O(64, 6) };
    getFrom(): capnp.Uint64 { return __S.getUint64(0, this); }
    setFrom(value: capnp.Uint64): void { __S.setUint64(0, value, this); }
    toString(): string { return "APIMessage_SyncRequest_" + super.toString(); }
}
export enum APIMessage_Which {
    SYNC_REQUEST = 3,
    NEW_ORDER_REQUEST = 0,
    ORDER_STATUS_REQUEST = 1,
    ACTIVE_ORDERS_REQUEST = 4,
    ORDER_CANCEL_REQUEST = 2,
    SYNC_STATUS = 5,
    ORDER_STATUS = 6,
    EXCHANGE = 7,
    INFO_MESSAGE = 8,
    BOOK = 9,
    BAR = 10,
    BAR_REQUEST = 11
}
export class APIMessage extends __S {
    static readonly SYNC_REQUEST = APIMessage_Which.SYNC_REQUEST;
    static readonly NEW_ORDER_REQUEST = APIMessage_Which.NEW_ORDER_REQUEST;
    static readonly ORDER_STATUS_REQUEST = APIMessage_Which.ORDER_STATUS_REQUEST;
    static readonly ACTIVE_ORDERS_REQUEST = APIMessage_Which.ACTIVE_ORDERS_REQUEST;
    static readonly ORDER_CANCEL_REQUEST = APIMessage_Which.ORDER_CANCEL_REQUEST;
    static readonly SYNC_STATUS = APIMessage_Which.SYNC_STATUS;
    static readonly ORDER_STATUS = APIMessage_Which.ORDER_STATUS;
    static readonly EXCHANGE = APIMessage_Which.EXCHANGE;
    static readonly INFO_MESSAGE = APIMessage_Which.INFO_MESSAGE;
    static readonly BOOK = APIMessage_Which.BOOK;
    static readonly BAR = APIMessage_Which.BAR;
    static readonly BAR_REQUEST = APIMessage_Which.BAR_REQUEST;
    static readonly _capnp = { displayName: "APIMessage", id: "d99512946cd0cd3f", size: new __O(64, 6) };
    getSyncRequest(): APIMessage_SyncRequest {
        __S.testWhich("syncRequest", __S.getUint16(16, this), 3, this);
        return __S.getAs(APIMessage_SyncRequest, this);
    }
    initSyncRequest(): APIMessage_SyncRequest {
        __S.setUint16(16, 3, this);
        return __S.getAs(APIMessage_SyncRequest, this);
    }
    isSyncRequest(): boolean { return __S.getUint16(16, this) === 3; }
    setSyncRequest(): void { __S.setUint16(16, 3, this); }
    getNewOrderRequest(): APIMessage_NewOrderRequest {
        __S.testWhich("newOrderRequest", __S.getUint16(16, this), 0, this);
        return __S.getAs(APIMessage_NewOrderRequest, this);
    }
    initNewOrderRequest(): APIMessage_NewOrderRequest {
        __S.setUint16(16, 0, this);
        return __S.getAs(APIMessage_NewOrderRequest, this);
    }
    isNewOrderRequest(): boolean { return __S.getUint16(16, this) === 0; }
    setNewOrderRequest(): void { __S.setUint16(16, 0, this); }
    getOrderStatusRequest(): APIMessage_OrderStatusRequest {
        __S.testWhich("orderStatusRequest", __S.getUint16(16, this), 1, this);
        return __S.getAs(APIMessage_OrderStatusRequest, this);
    }
    initOrderStatusRequest(): APIMessage_OrderStatusRequest {
        __S.setUint16(16, 1, this);
        return __S.getAs(APIMessage_OrderStatusRequest, this);
    }
    isOrderStatusRequest(): boolean { return __S.getUint16(16, this) === 1; }
    setOrderStatusRequest(): void { __S.setUint16(16, 1, this); }
    getActiveOrdersRequest(): APIMessage_ActiveOrdersRequest {
        __S.testWhich("activeOrdersRequest", __S.getUint16(16, this), 4, this);
        return __S.getAs(APIMessage_ActiveOrdersRequest, this);
    }
    initActiveOrdersRequest(): APIMessage_ActiveOrdersRequest {
        __S.setUint16(16, 4, this);
        return __S.getAs(APIMessage_ActiveOrdersRequest, this);
    }
    isActiveOrdersRequest(): boolean { return __S.getUint16(16, this) === 4; }
    setActiveOrdersRequest(): void { __S.setUint16(16, 4, this); }
    getOrderCancelRequest(): APIMessage_OrderCancelRequest {
        __S.testWhich("orderCancelRequest", __S.getUint16(16, this), 2, this);
        return __S.getAs(APIMessage_OrderCancelRequest, this);
    }
    initOrderCancelRequest(): APIMessage_OrderCancelRequest {
        __S.setUint16(16, 2, this);
        return __S.getAs(APIMessage_OrderCancelRequest, this);
    }
    isOrderCancelRequest(): boolean { return __S.getUint16(16, this) === 2; }
    setOrderCancelRequest(): void { __S.setUint16(16, 2, this); }
    getSyncStatus(): APIMessage_SyncStatus {
        __S.testWhich("syncStatus", __S.getUint16(16, this), 5, this);
        return __S.getAs(APIMessage_SyncStatus, this);
    }
    initSyncStatus(): APIMessage_SyncStatus {
        __S.setUint16(16, 5, this);
        return __S.getAs(APIMessage_SyncStatus, this);
    }
    isSyncStatus(): boolean { return __S.getUint16(16, this) === 5; }
    setSyncStatus(): void { __S.setUint16(16, 5, this); }
    getOrderStatus(): APIMessage_OrderStatus {
        __S.testWhich("orderStatus", __S.getUint16(16, this), 6, this);
        return __S.getAs(APIMessage_OrderStatus, this);
    }
    initOrderStatus(): APIMessage_OrderStatus {
        __S.setUint16(16, 6, this);
        return __S.getAs(APIMessage_OrderStatus, this);
    }
    isOrderStatus(): boolean { return __S.getUint16(16, this) === 6; }
    setOrderStatus(): void { __S.setUint16(16, 6, this); }
    getExchange(): APIMessage_Exchange {
        __S.testWhich("exchange", __S.getUint16(16, this), 7, this);
        return __S.getAs(APIMessage_Exchange, this);
    }
    initExchange(): APIMessage_Exchange {
        __S.setUint16(16, 7, this);
        return __S.getAs(APIMessage_Exchange, this);
    }
    isExchange(): boolean { return __S.getUint16(16, this) === 7; }
    setExchange(): void { __S.setUint16(16, 7, this); }
    getInfoMessage(): APIMessage_InfoMessage {
        __S.testWhich("infoMessage", __S.getUint16(16, this), 8, this);
        return __S.getAs(APIMessage_InfoMessage, this);
    }
    initInfoMessage(): APIMessage_InfoMessage {
        __S.setUint16(16, 8, this);
        return __S.getAs(APIMessage_InfoMessage, this);
    }
    isInfoMessage(): boolean { return __S.getUint16(16, this) === 8; }
    setInfoMessage(): void { __S.setUint16(16, 8, this); }
    getBook(): APIMessage_Book {
        __S.testWhich("book", __S.getUint16(16, this), 9, this);
        return __S.getAs(APIMessage_Book, this);
    }
    initBook(): APIMessage_Book {
        __S.setUint16(16, 9, this);
        return __S.getAs(APIMessage_Book, this);
    }
    isBook(): boolean { return __S.getUint16(16, this) === 9; }
    setBook(): void { __S.setUint16(16, 9, this); }
    getBar(): APIMessage_Bar {
        __S.testWhich("bar", __S.getUint16(16, this), 10, this);
        return __S.getAs(APIMessage_Bar, this);
    }
    initBar(): APIMessage_Bar {
        __S.setUint16(16, 10, this);
        return __S.getAs(APIMessage_Bar, this);
    }
    isBar(): boolean { return __S.getUint16(16, this) === 10; }
    setBar(): void { __S.setUint16(16, 10, this); }
    getBarRequest(): APIMessage_BarRequest {
        __S.testWhich("barRequest", __S.getUint16(16, this), 11, this);
        return __S.getAs(APIMessage_BarRequest, this);
    }
    initBarRequest(): APIMessage_BarRequest {
        __S.setUint16(16, 11, this);
        return __S.getAs(APIMessage_BarRequest, this);
    }
    isBarRequest(): boolean { return __S.getUint16(16, this) === 11; }
    setBarRequest(): void { __S.setUint16(16, 11, this); }
    toString(): string { return "APIMessage_" + super.toString(); }
    which(): APIMessage_Which { return __S.getUint16(16, this); }
}
APIMessage_Book._Bids = capnp.CompositeList(PriceLevel);
APIMessage_Book._Asks = capnp.CompositeList(PriceLevel);
